services:
  catalogoaberto:
    build: .
    ports:
      - "8080:80"

  database:
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    image: mariadb
    volumes:
      - "${PWD}/database_migrations/:/docker-entrypoint-initdb.d/"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
